#!/usr/bin/env python3
"""
Master script to generate all publication figures for the manuscript.

This script generates Figures 2-11 for the paper:
"The Paradox of Monumental Construction: Explaining Costly Signaling
as an Adaptive Response to Environmental Uncertainty"

Figures:
    1. Pacific Overview Map - External (not generated by this script)
    2. Price Equation for Multilevel Selection
    3. Frequency Comparison (explains frequency dimension of σ)
    4. Magnitude Comparison (explains magnitude dimension of σ)
    5. Combined Shortfall Scenarios (4-panel)
    6. Modified Price Equation Framework
    7. Model Dynamics Overview (4-panel)
    8. Environmental Phase Space Structure
    9. Validation of Price Equation Predictions (6-panel)
    10. Temporal Dynamics by Environmental Condition
    11. Rapa Nui vs. Rapa Iti Case Study Comparison

Usage:
    python scripts/generate_all_figures.py [--figures NUMS] [--output-dir DIR]

Examples:
    python scripts/generate_all_figures.py              # Generate all figures
    python scripts/generate_all_figures.py --figures 3 4 5   # Generate figures 3, 4, 5 only
    python scripts/generate_all_figures.py --figures 10      # Generate figure 10 only

Requirements:
    - Python 3.8+
    - numpy, matplotlib, scipy
    - costly package installed (pip install -e .)

Output:
    All figures are saved to figures/final/ as PNG files with 300 DPI.

Author: Carl P. Lipo, Robert J. DiNapoli, Terry L. Hunt
Date: January 2026
"""

import argparse
import subprocess
import sys
import time
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT / 'src'))

# Figure generation scripts mapping
FIGURE_SCRIPTS = {
    2: {
        'script': 'scripts/figure_generation/create_price_equation_figure.py',
        'output': 'figures/final/Figure_2_price_equation.png',
        'description': 'Price Equation for Multilevel Selection',
        'time_estimate': '5 seconds'
    },
    3: {
        'script': 'scripts/figure_generation/create_environmental_figures_moderate.py',
        'output': 'figures/final/Figure_3_frequency_comparison.png',
        'description': 'Frequency Comparison',
        'time_estimate': '10 seconds',
        'note': 'Also generates Figures 4 and 5'
    },
    4: {
        'script': None,  # Generated by Figure 3 script
        'output': 'figures/final/Figure_4_magnitude_comparison.png',
        'description': 'Magnitude Comparison',
        'generated_by': 3
    },
    5: {
        'script': None,  # Generated by Figure 3 script
        'output': 'figures/final/Figure_5_shortfall_scenarios.png',
        'description': 'Combined Shortfall Scenarios',
        'generated_by': 3
    },
    6: {
        'script': 'scripts/figure_generation/create_modified_price_equation.py',
        'output': 'figures/final/Figure_6_modified_price_equation.png',
        'description': 'Modified Price Equation Framework',
        'time_estimate': '10 seconds'
    },
    7: {
        'script': 'scripts/figure_generation/create_figure_2_model_dynamics.py',
        'output': 'figures/final/Figure_7_model_dynamics.png',
        'description': 'Model Dynamics Overview',
        'time_estimate': '5 seconds'
    },
    8: {
        'script': 'scripts/figure_generation/create_all_figures_colorblind.py',
        'output': 'figures/final/Figure_8_phase_space.png',
        'description': 'Environmental Phase Space Structure',
        'time_estimate': '2-5 minutes',
        'note': 'Also generates Figures 9, 10, 11 (uses simulation data)'
    },
    9: {
        'script': 'scripts/figure_generation/create_price_equation_validation.py',
        'output': 'figures/final/Figure_9_validation.png',
        'description': 'Validation of Price Equation Predictions',
        'time_estimate': '1-2 minutes'
    },
    10: {
        'script': 'scripts/figure_generation/create_figure_10_temporal_dynamics.py',
        'output': 'figures/final/Figure_10_temporal_dynamics.png',
        'description': 'Temporal Dynamics by Environmental Condition',
        'time_estimate': '2-3 minutes (runs 100 simulation replicates)'
    },
    11: {
        'script': None,  # Generated by Figure 8 script
        'output': 'figures/final/Figure_11_case_study.png',
        'description': 'Rapa Nui vs. Rapa Iti Case Study',
        'generated_by': 8
    }
}


def run_script(script_path: str, figure_num: int) -> bool:
    """
    Run a figure generation script.

    Args:
        script_path: Path to the Python script
        figure_num: Figure number for logging

    Returns:
        True if successful, False otherwise
    """
    full_path = PROJECT_ROOT / script_path

    if not full_path.exists():
        print(f"  ERROR: Script not found: {script_path}")
        return False

    try:
        result = subprocess.run(
            [sys.executable, str(full_path)],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            text=True,
            timeout=600  # 10 minute timeout
        )

        if result.returncode != 0:
            print(f"  ERROR: Script failed with return code {result.returncode}")
            if result.stderr:
                print(f"  STDERR: {result.stderr[:500]}")
            return False

        return True

    except subprocess.TimeoutExpired:
        print("  ERROR: Script timed out after 10 minutes")
        return False
    except Exception as e:
        print(f"  ERROR: {str(e)}")
        return False


def check_output(output_path: str) -> bool:
    """Check if output file exists and was recently modified."""
    full_path = PROJECT_ROOT / output_path
    return full_path.exists()


def generate_figure(fig_num: int, force: bool = False) -> bool:
    """
    Generate a single figure.

    Args:
        fig_num: Figure number (2-11)
        force: If True, regenerate even if output exists

    Returns:
        True if successful, False otherwise
    """
    if fig_num not in FIGURE_SCRIPTS:
        print(f"  ERROR: Unknown figure number {fig_num}")
        return False

    config = FIGURE_SCRIPTS[fig_num]

    # Check if this figure is generated by another script
    if config.get('generated_by'):
        parent = config['generated_by']
        print(f"  Note: Figure {fig_num} is generated by Figure {parent} script")
        return generate_figure(parent, force)

    # Check if output already exists
    if not force and check_output(config['output']):
        print(f"  Output exists: {config['output']}")
        print("  Use --force to regenerate")
        return True

    # Run the script
    script = config['script']
    if script:
        print(f"  Running: {script}")
        if 'time_estimate' in config:
            print(f"  Estimated time: {config['time_estimate']}")

        start_time = time.time()
        success = run_script(script, fig_num)
        elapsed = time.time() - start_time

        if success:
            print(f"  Completed in {elapsed:.1f} seconds")
            if check_output(config['output']):
                print(f"  Output: {config['output']}")
            return True
        return False

    return True


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Generate publication figures for the manuscript',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/generate_all_figures.py              # Generate all figures
    python scripts/generate_all_figures.py --figures 3 4 5   # Specific figures
    python scripts/generate_all_figures.py --figures 10 --force  # Force regenerate
        """
    )
    parser.add_argument(
        '--figures', '-f',
        type=int,
        nargs='+',
        default=None,
        help='Figure numbers to generate (default: all, 2-11)'
    )
    parser.add_argument(
        '--force',
        action='store_true',
        help='Force regeneration even if output exists'
    )
    parser.add_argument(
        '--list',
        action='store_true',
        help='List all figures and their scripts'
    )

    args = parser.parse_args()

    # List mode
    if args.list:
        print("\nFigure Generation Scripts")
        print("=" * 60)
        for num, config in sorted(FIGURE_SCRIPTS.items()):
            print(f"\nFigure {num}: {config['description']}")
            print(f"  Output: {config['output']}")
            if config.get('script'):
                print(f"  Script: {config['script']}")
            if config.get('generated_by'):
                print(f"  Generated by: Figure {config['generated_by']} script")
            if config.get('time_estimate'):
                print(f"  Time: {config['time_estimate']}")
            if config.get('note'):
                print(f"  Note: {config['note']}")
        return

    # Determine which figures to generate
    if args.figures:
        figures_to_generate = args.figures
    else:
        # Generate all figures (scripts that have their own script, not generated_by)
        figures_to_generate = [
            num for num, config in FIGURE_SCRIPTS.items()
            if config.get('script') is not None
        ]

    print("\n" + "=" * 60)
    print("GENERATING PUBLICATION FIGURES")
    print("=" * 60)
    print(f"\nProject root: {PROJECT_ROOT}")
    print("Output directory: figures/final/")
    print(f"Figures to generate: {figures_to_generate}")
    print()

    # Generate each figure
    results = {}
    total_start = time.time()

    for fig_num in sorted(set(figures_to_generate)):
        print(f"\n{'─' * 40}")
        print(f"Figure {fig_num}: {FIGURE_SCRIPTS[fig_num]['description']}")
        print('─' * 40)

        success = generate_figure(fig_num, force=args.force)
        results[fig_num] = success

    total_elapsed = time.time() - total_start

    # Summary
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)

    successful = [n for n, s in results.items() if s]
    failed = [n for n, s in results.items() if not s]

    print(f"\nTotal time: {total_elapsed:.1f} seconds")
    print(f"Successful: {len(successful)}/{len(results)}")

    if successful:
        print(f"\nGenerated figures: {successful}")

    if failed:
        print(f"\nFailed figures: {failed}")
        sys.exit(1)

    print("\nAll figures generated successfully!")
    print(f"Output directory: {PROJECT_ROOT / 'figures' / 'final'}")


if __name__ == '__main__':
    main()
